// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ShipmentManaging.proto

package tmsmanagerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShipmentStatus int32

const (
	ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED ShipmentStatus = 0
	ShipmentStatus_SHIPMENT_STATUS_PENDING     ShipmentStatus = 1
	ShipmentStatus_SHIPMENT_STATUS_PICKED_UP   ShipmentStatus = 2
	ShipmentStatus_SHIPMENT_STATUS_IN_TRANSIT  ShipmentStatus = 3
	ShipmentStatus_SHIPMENT_STATUS_DELIVERED   ShipmentStatus = 4
)

// Enum value maps for ShipmentStatus.
var (
	ShipmentStatus_name = map[int32]string{
		0: "SHIPMENT_STATUS_UNSPECIFIED",
		1: "SHIPMENT_STATUS_PENDING",
		2: "SHIPMENT_STATUS_PICKED_UP",
		3: "SHIPMENT_STATUS_IN_TRANSIT",
		4: "SHIPMENT_STATUS_DELIVERED",
	}
	ShipmentStatus_value = map[string]int32{
		"SHIPMENT_STATUS_UNSPECIFIED": 0,
		"SHIPMENT_STATUS_PENDING":     1,
		"SHIPMENT_STATUS_PICKED_UP":   2,
		"SHIPMENT_STATUS_IN_TRANSIT":  3,
		"SHIPMENT_STATUS_DELIVERED":   4,
	}
)

func (x ShipmentStatus) Enum() *ShipmentStatus {
	p := new(ShipmentStatus)
	*p = x
	return p
}

func (x ShipmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShipmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ShipmentManaging_proto_enumTypes[0].Descriptor()
}

func (ShipmentStatus) Type() protoreflect.EnumType {
	return &file_ShipmentManaging_proto_enumTypes[0]
}

func (x ShipmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShipmentStatus.Descriptor instead.
func (ShipmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_ShipmentManaging_proto_rawDescGZIP(), []int{0}
}

type CreateShipmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceNumber string                 `protobuf:"bytes,1,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Origin          string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination     string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	DriverName      string                 `protobuf:"bytes,4,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	UnitNumber      string                 `protobuf:"bytes,5,opt,name=unit_number,json=unitNumber,proto3" json:"unit_number,omitempty"`
	ShipmentAmount  float64                `protobuf:"fixed64,6,opt,name=shipment_amount,json=shipmentAmount,proto3" json:"shipment_amount,omitempty"`
	DriverRevenue   float64                `protobuf:"fixed64,7,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_ShipmentManaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShipmentManaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_ShipmentManaging_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShipmentRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreateShipmentRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CreateShipmentRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateShipmentRequest) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *CreateShipmentRequest) GetUnitNumber() string {
	if x != nil {
		return x.UnitNumber
	}
	return ""
}

func (x *CreateShipmentRequest) GetShipmentAmount() float64 {
	if x != nil {
		return x.ShipmentAmount
	}
	return 0
}

func (x *CreateShipmentRequest) GetDriverRevenue() float64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

type GetShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_ShipmentManaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShipmentManaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_ShipmentManaging_proto_rawDescGZIP(), []int{1}
}

func (x *GetShipmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status        ShipmentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=tmsmanagerpb.v1.ShipmentStatus" json:"status,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEventRequest) Reset() {
	*x = AddEventRequest{}
	mi := &file_ShipmentManaging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventRequest) ProtoMessage() {}

func (x *AddEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShipmentManaging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventRequest.ProtoReflect.Descriptor instead.
func (*AddEventRequest) Descriptor() ([]byte, []int) {
	return file_ShipmentManaging_proto_rawDescGZIP(), []int{2}
}

func (x *AddEventRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *AddEventRequest) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *AddEventRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_ShipmentManaging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShipmentManaging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_ShipmentManaging_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type ShipmentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,2,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Origin          string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination     string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Status          ShipmentStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=tmsmanagerpb.v1.ShipmentStatus" json:"status,omitempty"`
	DriverName      string                 `protobuf:"bytes,6,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	UnitNumber      string                 `protobuf:"bytes,7,opt,name=unit_number,json=unitNumber,proto3" json:"unit_number,omitempty"`
	ShipmentAmount  float64                `protobuf:"fixed64,8,opt,name=shipment_amount,json=shipmentAmount,proto3" json:"shipment_amount,omitempty"`
	DriverRevenue   float64                `protobuf:"fixed64,9,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShipmentResponse) Reset() {
	*x = ShipmentResponse{}
	mi := &file_ShipmentManaging_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentResponse) ProtoMessage() {}

func (x *ShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShipmentManaging_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentResponse.ProtoReflect.Descriptor instead.
func (*ShipmentResponse) Descriptor() ([]byte, []int) {
	return file_ShipmentManaging_proto_rawDescGZIP(), []int{4}
}

func (x *ShipmentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShipmentResponse) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *ShipmentResponse) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *ShipmentResponse) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ShipmentResponse) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *ShipmentResponse) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *ShipmentResponse) GetUnitNumber() string {
	if x != nil {
		return x.UnitNumber
	}
	return ""
}

func (x *ShipmentResponse) GetShipmentAmount() float64 {
	if x != nil {
		return x.ShipmentAmount
	}
	return 0
}

func (x *ShipmentResponse) GetDriverRevenue() float64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

func (x *ShipmentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ShipmentResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ShipmentEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_ShipmentManaging_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShipmentManaging_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_ShipmentManaging_proto_rawDescGZIP(), []int{5}
}

func (x *HistoryResponse) GetEvents() []*ShipmentEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ShipmentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        ShipmentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=tmsmanagerpb.v1.ShipmentStatus" json:"status,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentEvent) Reset() {
	*x = ShipmentEvent{}
	mi := &file_ShipmentManaging_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentEvent) ProtoMessage() {}

func (x *ShipmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ShipmentManaging_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentEvent.ProtoReflect.Descriptor instead.
func (*ShipmentEvent) Descriptor() ([]byte, []int) {
	return file_ShipmentManaging_proto_rawDescGZIP(), []int{6}
}

func (x *ShipmentEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShipmentEvent) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *ShipmentEvent) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *ShipmentEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_ShipmentManaging_proto protoreflect.FileDescriptor

const file_ShipmentManaging_proto_rawDesc = "" +
	"\n" +
	"\x16ShipmentManaging.proto\x12\x0ftmsmanagerpb.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x02\n" +
	"\x15CreateShipmentRequest\x12)\n" +
	"\x10reference_number\x18\x01 \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x1f\n" +
	"\vdriver_name\x18\x04 \x01(\tR\n" +
	"driverName\x12\x1f\n" +
	"\vunit_number\x18\x05 \x01(\tR\n" +
	"unitNumber\x12'\n" +
	"\x0fshipment_amount\x18\x06 \x01(\x01R\x0eshipmentAmount\x12%\n" +
	"\x0edriver_revenue\x18\a \x01(\x01R\rdriverRevenue\"$\n" +
	"\x12GetShipmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x7f\n" +
	"\x0fAddEventRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.tmsmanagerpb.v1.ShipmentStatusR\x06status\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"4\n" +
	"\x11GetHistoryRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"\xc8\x03\n" +
	"\x10ShipmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10reference_number\x18\x02 \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x127\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1f.tmsmanagerpb.v1.ShipmentStatusR\x06status\x12\x1f\n" +
	"\vdriver_name\x18\x06 \x01(\tR\n" +
	"driverName\x12\x1f\n" +
	"\vunit_number\x18\a \x01(\tR\n" +
	"unitNumber\x12'\n" +
	"\x0fshipment_amount\x18\b \x01(\x01R\x0eshipmentAmount\x12%\n" +
	"\x0edriver_revenue\x18\t \x01(\x01R\rdriverRevenue\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"I\n" +
	"\x0fHistoryResponse\x126\n" +
	"\x06events\x18\x01 \x03(\v2\x1e.tmsmanagerpb.v1.ShipmentEventR\x06events\"\xa9\x01\n" +
	"\rShipmentEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.tmsmanagerpb.v1.ShipmentStatusR\x06status\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt*\xac\x01\n" +
	"\x0eShipmentStatus\x12\x1f\n" +
	"\x1bSHIPMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SHIPMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19SHIPMENT_STATUS_PICKED_UP\x10\x02\x12\x1e\n" +
	"\x1aSHIPMENT_STATUS_IN_TRANSIT\x10\x03\x12\x1d\n" +
	"\x19SHIPMENT_STATUS_DELIVERED\x10\x042\xdf\x02\n" +
	"\x0fShipmentService\x12[\n" +
	"\x0eCreateShipment\x12&.tmsmanagerpb.v1.CreateShipmentRequest\x1a!.tmsmanagerpb.v1.ShipmentResponse\x12U\n" +
	"\vGetShipment\x12#.tmsmanagerpb.v1.GetShipmentRequest\x1a!.tmsmanagerpb.v1.ShipmentResponse\x12D\n" +
	"\bAddEvent\x12 .tmsmanagerpb.v1.AddEventRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\n" +
	"GetHistory\x12\".tmsmanagerpb.v1.GetHistoryRequest\x1a .tmsmanagerpb.v1.HistoryResponseB:Z8github.com/nurtikaga/tms_proj/tms-protos/go;tmsmanagerpbb\x06proto3"

var (
	file_ShipmentManaging_proto_rawDescOnce sync.Once
	file_ShipmentManaging_proto_rawDescData []byte
)

func file_ShipmentManaging_proto_rawDescGZIP() []byte {
	file_ShipmentManaging_proto_rawDescOnce.Do(func() {
		file_ShipmentManaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ShipmentManaging_proto_rawDesc), len(file_ShipmentManaging_proto_rawDesc)))
	})
	return file_ShipmentManaging_proto_rawDescData
}

var file_ShipmentManaging_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ShipmentManaging_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ShipmentManaging_proto_goTypes = []any{
	(ShipmentStatus)(0),           // 0: tmsmanagerpb.v1.ShipmentStatus
	(*CreateShipmentRequest)(nil), // 1: tmsmanagerpb.v1.CreateShipmentRequest
	(*GetShipmentRequest)(nil),    // 2: tmsmanagerpb.v1.GetShipmentRequest
	(*AddEventRequest)(nil),       // 3: tmsmanagerpb.v1.AddEventRequest
	(*GetHistoryRequest)(nil),     // 4: tmsmanagerpb.v1.GetHistoryRequest
	(*ShipmentResponse)(nil),      // 5: tmsmanagerpb.v1.ShipmentResponse
	(*HistoryResponse)(nil),       // 6: tmsmanagerpb.v1.HistoryResponse
	(*ShipmentEvent)(nil),         // 7: tmsmanagerpb.v1.ShipmentEvent
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_ShipmentManaging_proto_depIdxs = []int32{
	0,  // 0: tmsmanagerpb.v1.AddEventRequest.status:type_name -> tmsmanagerpb.v1.ShipmentStatus
	0,  // 1: tmsmanagerpb.v1.ShipmentResponse.status:type_name -> tmsmanagerpb.v1.ShipmentStatus
	8,  // 2: tmsmanagerpb.v1.ShipmentResponse.created_at:type_name -> google.protobuf.Timestamp
	8,  // 3: tmsmanagerpb.v1.ShipmentResponse.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 4: tmsmanagerpb.v1.HistoryResponse.events:type_name -> tmsmanagerpb.v1.ShipmentEvent
	0,  // 5: tmsmanagerpb.v1.ShipmentEvent.status:type_name -> tmsmanagerpb.v1.ShipmentStatus
	8,  // 6: tmsmanagerpb.v1.ShipmentEvent.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 7: tmsmanagerpb.v1.ShipmentService.CreateShipment:input_type -> tmsmanagerpb.v1.CreateShipmentRequest
	2,  // 8: tmsmanagerpb.v1.ShipmentService.GetShipment:input_type -> tmsmanagerpb.v1.GetShipmentRequest
	3,  // 9: tmsmanagerpb.v1.ShipmentService.AddEvent:input_type -> tmsmanagerpb.v1.AddEventRequest
	4,  // 10: tmsmanagerpb.v1.ShipmentService.GetHistory:input_type -> tmsmanagerpb.v1.GetHistoryRequest
	5,  // 11: tmsmanagerpb.v1.ShipmentService.CreateShipment:output_type -> tmsmanagerpb.v1.ShipmentResponse
	5,  // 12: tmsmanagerpb.v1.ShipmentService.GetShipment:output_type -> tmsmanagerpb.v1.ShipmentResponse
	9,  // 13: tmsmanagerpb.v1.ShipmentService.AddEvent:output_type -> google.protobuf.Empty
	6,  // 14: tmsmanagerpb.v1.ShipmentService.GetHistory:output_type -> tmsmanagerpb.v1.HistoryResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ShipmentManaging_proto_init() }
func file_ShipmentManaging_proto_init() {
	if File_ShipmentManaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ShipmentManaging_proto_rawDesc), len(file_ShipmentManaging_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ShipmentManaging_proto_goTypes,
		DependencyIndexes: file_ShipmentManaging_proto_depIdxs,
		EnumInfos:         file_ShipmentManaging_proto_enumTypes,
		MessageInfos:      file_ShipmentManaging_proto_msgTypes,
	}.Build()
	File_ShipmentManaging_proto = out.File
	file_ShipmentManaging_proto_goTypes = nil
	file_ShipmentManaging_proto_depIdxs = nil
}
